title: Jekyll Simple Dark
email: sonlink.dourden@gmail.com
description: > # Mi blog personal donde hablo de mis proyectos, tutoriales, etc, ademas de exponer mis trabajos y proyectos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://son-link.github.io/jekyll-simple-dark/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM

# Social Network
social_links: true # If true show social links
facebook: 'https://www.facebook.com/Son-Link-Blog-159172270839305/?ref=your_pages'
twitter: 'https://twitter.com/sonlink'
github: 'https://github.com/son-link'
